### PR TITLE
Make `import Cassette` work on Julia 1.12 (although the package probably won't work on 1.12)

### LINKED ISSUE #209: Cannot precompile Cassette.jl on Julia nightly (1.12)
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.12.0-DEV.1440 (2024-10-21)
 _/ |\__'_|_|_|\__'_|  |  Commit a4a4b954450 (0 days old master)
|__/                   |

julia> import Cassette
Info Given Cassette was explicitly requested, output will be shown live
ERROR: LoadError: FieldError: type CodeInfo has no field `linetable`, available fields: `code`, `debuginfo`, `ssavaluetypes`, `ssaflags`, `slotnames`, `slotflags`, `slottypes`, `rettype`, `parent`, `edges`, `min_world`, `max_world`, `method_for_inference_limit_heuristics`, `nargs`, `propagate_inbounds`, `has_fcall`, `nospecializeinfer`, `isva`, `inlining`, `constprop`, `purity`, `inlining_cost`
Stacktrace:
  [1] getproperty(ci::Core.CodeInfo, s::Symbol)
    @ Base ./deprecated.jl:461
  [2] verbose_lineinfo!(ci::Core.CodeInfo, sig::Type{<:Tuple})
    @ Cassette ~/.julia/packages/Cassette/4UsSX/src/overdub.jl:53
  [3] reflect(sigtypes::Tuple, world::UInt64)
    @ Cassette ~/.julia/packages/Cassette/4UsSX/src/overdub.jl:128
  [4] reflect(sigtypes::Tuple)
    @ Cassette ~/.julia/packages/Cassette/4UsSX/src/overdub.jl:89
  [5] top-level scope
    @ ~/.julia/packages/Cassette/4UsSX/src/overdub.jl:599
  [6] include(mod::Module, _path::String)
    @ Base ./Base.jl:582
  [7] include(x::String)
    @ Cassette ~/.julia/packages/Cassette/4UsSX/src/Cassette.jl:1
  [8] top-level scope
    @ ~/.julia/packages/Cassette/4UsSX/src/Cassette.jl:8
  [9] include
    @ ./Base.jl:582 [inlined]
 [10] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2947
 [11] top-level scope
    @ stdin:5
 [12] eval
    @ ./boot.jl:459 [inlined]
 [13] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:2798
 [14] include_string
    @ ./loading.jl:2808 [inlined]
 [15] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:327
 [16] _start()
    @ Base ./client.jl:558
in expression starting at /Users/dilum/.julia/packages/Cassette/4UsSX/src/overdub.jl:598
in expression starting at /Users/dilum/.julia/packages/Cassette/4UsSX/src/Cassette.jl:1
in expression starting at stdin:5
```

### PR DESCRIPTION
**Pull request by DilumAluthge**
Closes #209

This won't make Cassette.jl actually work on Julia 1.12, but it makes `import Cassette` work without error on Julia 1.12.

So, if you have Cassette.jl deep somewhere in your dependency tree, but you don't actually use Cassette (as is my use case), now you will be able to precompile your entire project without error.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
cc: @vchuravy

**Comment by DilumAluthge** [comment]
Thanks @vchuravy!
